// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awfdcqpirekpkmbowtwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3ZmRjcXBpcmVrcGttYm93dHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjA2NjQsImV4cCI6MjA2NjMzNjY2NH0.weTev6R7BqeXNOezDcDW2XkChSjdv-x5Oh0Rp7mcGuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);