// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwpfcduymdbdjnzpeqvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3cGZjZHV5bWRiZGpuenBlcXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDMzMjIsImV4cCI6MjA1NjY3OTMyMn0.QiqGHpvbql0EFoLka7oPVroUTKcqMos3CLVajW36dSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);